default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: diary_api_development
test:
  <<: *default
  database: diary_api_test
production:
  <<: *default
  database: diary_api_production
  username: diary_api
  password: <%= ENV['DIARY_API_DATABASE_PASSWORD'] %>
